version: '3.7'

services:
  ### PHP-FPM Container #######################################
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        user: user
        uid: 1000
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php7.4.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - "8000"
      - "9000"
      - "9001"
    extra_hosts:
      # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "dockerhost:172.17.0.1"
    environment:
      # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
      - PHP_IDE_CONFIG=serverName=localhost
      - XDEBUG_CONFIG=remote_host=172.17.0.1
    networks:
      - app-network
    restart: always

  ### Nginx Server Container ##################################
  nginx:
    build:
      context: ./docker/nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes:
      - .:/var/www/html
      - ./docker/nginx/timeout.conf:/etc/nginx/conf.d/timeout.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network

  ### Database MySql Container ##################################
  db_mysql:
      image: mysql:5.7.22
      restart: always
      environment:
        MYSQL_DATABASE: develop
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_PASSWORD: 123456
        MYSQL_USER: root
      volumes:
        - ./docker/mysql/dbdata:/var/lib/mysql
      ports:
        - "3306:3306"
      container_name: transfer
      networks:
        - app-network

### Memcached Container ##################################
#  memcached:
#    container_name: memcached
#    image: memcached:latest
#    ports:
#        - "11211:11211"
#    environment:
#      - MEMCACHED_USERNAME=memcached
#      - MEMCACHED_PASSWORD=123456
#    restart: always
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
